# Generated by Django 2.0.6 on 2018-06-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20180607_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
